#!/bin/sh
#
# Copyright (C) 2021 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

while [ $# -gt 0 ]; do
    case $1 in
    --)
        shift
        break
        ;;
    -l|--command-log)
        COMMAND_LOG=$2
        shift  # past argument
        shift  # past value
        ;;
    *)
        break
        ;;
    esac
done

# Handle the command log
#
# Due to the interceptor being active from any working directory, we need to
# capture the current working directory and make the command log path absolute.
if [ -n "$COMMAND_LOG" ]; then
    export INTERCEPTOR_command_log=$(realpath $COMMAND_LOG)
    echo "[" > "$INTERCEPTOR_command_log"
fi

# Discover the interceptor preload library
export LD_PRELOAD=$(realpath $(dirname $(readlink -f $0))/../lib64/libinterceptor.so)
if [ ! -x "$LD_PRELOAD" ]; then
    echo "Interceptor library can't be found at: $LD_PRELOAD" >&2
    exit 1
fi

# Spawn the actual command in a subshell to capture possibly set environment
# variables, e.g. `interceptor MY_ENV=123 command_to_execute`
sh -c "$*"

if [ -n "$COMMAND_LOG" ]; then
    echo "]" >> "$INTERCEPTOR_command_log"
fi
